name: CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and deploy docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          envs: GH_TOKEN, ENV_FILE_BASE64
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            GH_TOKEN=${{ github.token }}
            ENV_FILE_BASE64=${{ secrets.ENV_FILE_BASE64 }}

            echo "----- DEPLOYMENT STARTED -----"

            cd /opt
            
            # Reset project folder
            rm -rf kap || true

            # Clone latest code
            git clone https://Tahiri1997:${GH_TOKEN}@github.com/Tahiri1997/devops.git kap

            cd kap
            git checkout main

            # Restore .env
            echo "${ENV_FILE_BASE64}" | base64 -d > .env

            # Stop + remove running containers
            docker compose down || true
            docker rm -f contacts_frontend || true
            docker rm -f contacts_backend || true
            docker rm -f contacts_db || true

            # Rebuild and start
            docker compose up -d --build

            docker ps
            echo "----- DEPLOYMENT COMPLETED -----"
